### ISSUE TITLE
Trustee Domain UST Setup - Extra users added to primary organization!

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe-apiplatform/user-sync.py#335]
I have users A, B, C in "All-Apps" and D, E, F are in "Andrew-All-Apps" security groups. And I want to sync "All-Apps" to primary and "Andrew-All-Apps" to secondary console. 

After sync, users A, B, C, **D, E, F** got added to primary organization (users tab). In my understanding **D, E, F** are extra users in primary organization. Is that expected behavior?

Additional Info, 
- only users A, B, C got correct group assignment in primary and users D, E, F in secondary organization.
- you cannot specify a prefix or shortname for primary organization in *connectors* or *adobe_groups*  

I am using UST v2.2.2 and have following setup. 

```
  connectors:
    umapi: 
     - "./stage/connector-umapi.yml"
     - andrew: "./andrew/connector-umapi.yml"
  groups:
    - directory_group: "All-Apps Users"
      adobe_groups:
        - "All-Apps-Users"
    - directory_group: "Andrew-All-Apps Users"
      adobe_groups:
        - "andrew::AtifTestGroup"
```

> 2018-01-31 14:12:32 3156 INFO processor -   Number of primary UMAPI actions sent (total, success, error): (6, 6, 0)
2018-01-31 14:12:32 3156 INFO processor -    Number of andrew UMAPI actions sent (total, success, error): (3, 3, 0)

[2018-01-31.log](https://github.com/adobe-apiplatform/user-sync.py/files/1683117/2018-01-31.log)
