### ISSUE TITLE
Unable to use encrypted private key

### ISSUE THREAD

**Issue by joker32** [adobe-apiplatform/user-sync.py#453]
Platform: Windows Server 2016
Python: 3.6.8 x64

Using a encrypted private RSA key with user-sync 2.4 fails with error message:
CRITICAL main - umapi configuration.enterprise: Error decrypting private key, either the password is wrong or: RSA key format is not supported

Error occurs with keypass either in Windows Credential Manager or plain text keypass in file, ie:
secure_priv_key_pass_key: umapi_private_key_passphrase
or
priv_key_pass: "xxx"

Unencrypted private key works correctly. 

Key generation:
https://www.adobe.io/apis/experienceplatform/console/authentication/gettingstarted.html#!adobeio/adobeio-documentation/master/console/createcert.md

Encrypted key created using OpenSSL:
openssl pkcs8 -in private.key -topk8 -v2 des3 -out private-encrypted.key

User Sync Tool - common errors - Error decrypting private key:
https://helpx.adobe.com/enterprise/kb/UMAPI-UST.html#

Could be related to: #313

**Comment by Luci2015** [comment]
Hi,
If the unencrypted file works, I'm pretty sure it's all related to how you created the generic credential storing the pass of the encrypted private key and the config file setting.

Try this
_________
Make your connector-umapi.yml file to have these lines active:

```
enterprise:
  org_id: "some value @ AdobeOrg"
  api_key: "some value"
  client_secret: "some value"
  tech_acct: "some value @techacct.adobe.com"
  priv_key_path: "private-encrypted.key"
  secure_priv_key_pass_key: umapi_private_key_passphrase
```
(make sure the encrypted file name is correct and in same folder as the .pex file, otherwise you'll need full path to it)

Next open the Windows Credential Manager  - Windows Credentials and create a new generic credential.
You'll be asked for:
Internet or network address -> paste in there **umapi_private_key_passphrase**
User name: -> paste in there the OrgID value
Password: -> type in the password used to encrypt the file.
