### ISSUE TITLE
Group processing is failing if only additional_groups is defined

### ISSUE THREAD

**Issue by pierresteiner** [adobe-apiplatform/user-sync.py#508]
Connector: Okta
Version 2.5.0
Error message:  CRITICAL main - Value not found for key: directory_group in: <user-sync-config.yml>.directory_users.groups.[0]

Relevant part from config file:
````yaml
connectors:
  groups:
    additional_groups:
      - source: "Adobe-(.+)"
        target: "Adobe-(\\1)"
invocation_defaults:
  process_groups: Yes
  users: ['group','somegroup']
````

Since we are doing all our mapping dynamically, there is no need for "directory_group" elements in the config
