### ISSUE TITLE
When user duplicate accounts (adobe id and federated id), UST fails to de-provision federated account

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe-apiplatform/user-sync.py#624]
1.	User has duplicate accounts in console (one as Adobe ID and other as Federated ID)
- Adobe ID is a Org Admin with no group assignments
- Federated ID is not a Org Admin and has group assignment (“acl-acrobat”) from UST
2.	I remove the user from corresponding security group (“acl-acrobat”) in AD
3.	**Now I run UST but the user’s groups assignment doesn’t get removed and remains in console!**

Environment: 

- Username based SSO and has windows UST v2.5.1. 
- Dynamic group mapping Enabled (happen even when dynamic group mapping is disabled). 
- Adobe ID excluded by default. 

Please find config attached.
```
adobe_users:
  exclude_identity_types:
    - adobeID
  exclude_adobe_groups: null
  exclude_users: 
    - ".*@emeapobadfs.com"
    - ".*@sgltest.onmicrosoft.com"
    - ".*@adobeccetest2.onmicrosoft.com"
    - ".*@ccestestdomain2.com"
    #- "bajwauser"
  connectors:
    umapi: connector-umapi.yml
directory_users:
  user_identity_type: federatedID
  default_country_code: GB
  connectors:
    ldap: connector-ldap.yml
  groups:
    - directory_group: acl-adobecloud
      adobe_groups:
        - acl-adobecloud
#  additional_groups:
#    - source: "acl-(.+)"
#      target: "acl-\\1"
  group_sync_options:
    auto_create: True
limits:
  max_adobe_only_users: 200
logging:
  log_to_file: true
  file_log_directory: logs
  file_log_name_format: '{:%Y-%m-%d}.log'
  file_log_level: debug
  console_log_level: info
invocation_defaults:
  adobe_only_user_action: delete
  adobe_only_user_list: null
  connector: ldap
  process_groups: Yes
  strategy: sync
  test_mode: No
  update_user_info: No
  user_filter: null
  users: mapped
  adobe_users: all
```
[myTestLogs_2020-08-05.log](https://github.com/adobe-apiplatform/user-sync.py/files/5109840/myTestLogs_2020-08-05.log)
