### ISSUE TITLE
Can't get disabled users to deprovision

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/user-sync.py#9]
I'm testing the sync tool with a couple of users that I've synced from my Active Directory sandbox.  I was able to create and provision them successfully.

![test users](https://cloud.githubusercontent.com/assets/25495410/22534503/cbb398d8-e8b1-11e6-84a1-36b855dea335.PNG)

When I mark those users as disabled in my sandbox AD, the sync tool doesn't do anything to deprovision them.

Here's the log I get when I run it after disabling the users in AD:

[log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/746673/log.txt)

What I expect to happen, since I'm not running with the "remove users" option, is for the disabled accounts to have their product entitlements removed, essentially disabling those accounts in the admin console.

For reference, here is my product config.  I've ensured that those users only belong to product config groups that are mapped in the config file.

```yaml
    - directory_group: ADOBE-ALL-APPS
      dashboard_groups:
        - All Apps
    - directory_group: ADOBE-PHOTOSHOP
      dashboard_groups:
        - Photoshop
    - directory_group: ADOBE-VIDEO
      dashboard_groups:
        - Default Custom plan - Video - 6 GB configuration
```
